#!/bin/sh
#  Copyright (C) 2025, STMicroelectronics - All Rights Reserved

# shellcheck disable=SC2034
NAT64=1
DNS64=0
DHCPV6_PD=0
DHCPV6_PD_REF=0
NETWORK_MANAGER=0
BACKBONE_ROUTER=1
BORDER_ROUTING=1
WEB_GUI=1
REST_API=1
FIREWALL=0
#
# Specific variables used by setup to initialize OTBR
NO_SUDO=1
NO_SWAPFILE=1
