# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "x-linux-otbr-posix"
BBFILE_PATTERN_x-linux-otbr-posix = "^${LAYERDIR}/"
BBFILE_PRIORITY_x-linux-otbr-posix = "5"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_x-linux-otbr-posix = "1"
LAYERSERIES_COMPAT_x-linux-otbr-posix = "scarthgap"

LAYERDEPENDS_x-linux-otbr-posix = "stm-st-stm32mp"
LAYERDEPENDS_x-linux-otbr-posix += "st-openstlinux"

# OpenSTLinux compatibility version
ST_OSTL_COMPATIBILITY_VERSION_x-linux-otbr-posix = "6.1"
